version: '3'
services:
  backend:
    container_name: node-docker-ci-cd
    build:
      context: .
      dockerfile: Dockerfile
    image: node-docker-ci-cd
    ports:
      - 3010:3000
    volumes:
      - ./src:/app/src
    env_file:
      - ./.env
    environment:
      - CHOKIDAR_USEPOLLING=true
      - NODE_ENV=dev
      - APP_PORT=${APP_PORT}