version: '3'
services:
  backend:
    container_name: nodejs-backend
    build:
      context: .
      args:
        - NODE_ENV=dev
      dockerfile: Dockerfile
    image: node-docker-ci-cd
    ports:
      - 3010:${APP_PORT}
    volumes:
      - ./:/app
      - /app/node_modules
    env_file:
      - ./.env
    environment:
      - CHOKIDAR_USEPOLLING=true
      - NODE_ENV=dev
      - APP_PORT=${APP_PORT}
    depends_on:
      - postgres
    links:
      - postgres
    command: npm run dev

  postgres:
    image: postgres:14.1-alpine
    container_name: postgres-db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes: 
      - postgres-db:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/create_tables.sql

volumes:
  postgres-db:
    driver: local