version: '3'
services:
  backend:
    container_name: nodejs-backend
    build:
      context: .
      args:
        - NODE_ENV=dev
      dockerfile: Dockerfile
    image: node-docker-ci-cd
    #ports:
    #  - ${APP_PORT_EXPOSE}:${APP_PORT}
    volumes:
      - ./:/app
      - /app/node_modules
    env_file:
      - ./.env
    environment:
      - CHOKIDAR_USEPOLLING=true
      - NODE_ENV=dev
    depends_on:
      - postgres
    command: npm run dev

  postgres:
    image: postgres:14.1-alpine
    container_name: postgres-db
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    env_file:
      - ./.env
    #ports:
    #  - '${DB_PORT}:5432'
    volumes: 
      - postgres-db:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/create_tables.sql

  nginx:
    image: nginx:stable-alpine
    container_name: nginx-proxy
    restart: always
    environment:
      - APP_PORT=${APP_PORT}
    env_file:
      - ./.env
    ports:
      - '${NGINX_PORT}:80'
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/custom_404.html:/usr/share/nginx/html/custom_404.html
    depends_on:
      - backend


volumes:
  postgres-db:
    driver: local